// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.xebia.shortnotes.domain;

import com.xebia.shortnotes.domain.NoteIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect NoteIntegrationTest_Roo_Configurable {
    
    declare @type: NoteIntegrationTest: @Configurable;
    
}
